// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srvwhyvkmheqhectyghl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNydndoeXZrbWhlcWhlY3R5Z2hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4NDk1ODUsImV4cCI6MjA0OTQyNTU4NX0.9NRmQjmgkbG8GibOppjRlZDB7BTxp0KHP2kQyOdZ-ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);